<h1 style="font-family: 'Georgia', serif; text-align: center; font-weight: normal; margin-bottom: 0px;">
  <em>Coding Activation Function</em>
</h1>
<p style="text-align: center; font-family: 'Georgia', serif; color: gray; margin-top: 5px;">
  ReLU & Softmax
</p>
<hr style="width: 50%; border: 1px solid #ddd;">

<center>
    <img src="Note-Images/activation-1.jpg">
</center>

<center>
    <img src="Note-Images/activation-2.jpg">
</center>

# ReLU Function

In [5]:
import numpy as np

In [21]:
# Suppose from a particular layer the output is O

def ReLU(inputs):
    output = np.maximum(0, inputs)
    return output

O = [[0.5,-0.4, 0.3],
     [0.45,0.4, -0.3],
     [-0.35, 0.2, 0.15]]

O = np.array((O))

final_output = ReLU(O)

print(final_output)
    

[[0.5  0.   0.3 ]
 [0.45 0.4  0.  ]
 [0.   0.2  0.15]]


# Softmax Function

In [31]:
def Softmax(inputs):
    #unnormalized probabilities
    value = inputs - np.max(inputs, axis = 1, keepdims = True)
    exp_val = np.exp(value)
    #Generating Probabilities with softmax formula
    Output = exp_val / np.sum(exp_val, axis = 1, keepdims = True)
    return Output

O = [[0.5,-0.4, 0.3],
     [0.45,0.4, -0.3],
     [-0.35, 0.2, 0.15]]

O = np.array((O))

final_output = Softmax(O)

print(final_output)

[[0.44937753 0.18270327 0.3679192 ]
 [0.41261003 0.3924868  0.19490318]
 [0.22820764 0.39554158 0.37625079]]
